============================= test session starts ==============================
platform darwin -- Python 3.11.2, pytest-7.4.2, pluggy-1.3.0
rootdir: /Users/alikhan/Documents/Lambton_College/3rd_semester/CI:CD/CA_1/regression_project
plugins: cov-4.1.0
collected 4 items

tests/test_regression_project.py ..F.                                    [100%]WARNING: Failed to generate report: No data to report.



=================================== FAILURES ===================================
________________________ test_regression_model_training ________________________

regression_data = (array([[5.48813504e-01],
       [7.15189366e-01],
       [6.02763376e-01],
       [5.44883183e-01],
       [4.2365479...2.51379489],
       [1.19438701],
       [1.85012794],
       [2.79659873],
       [1.47661446],
       [2.4840165 ]]))
regression_model = <keras.src.engine.sequential.Sequential object at 0x14eedc450>

    def test_regression_model_training(regression_data, regression_model):
        X_train, y_train = regression_data
        loss = regression_model.evaluate(X_train, y_train)
>       assert loss < 0.1  # Adjust as needed
E       assert 6.849613666534424 < 0.1

tests/test_regression_project.py:33: AssertionError
---------------------------- Captured stdout setup -----------------------------
 1/32 [..............................] - ETA: 1:05 - loss: 6.335916/32 [==============>...............] - ETA: 0s - loss: 7.1793  30/32 [===========================>..] - ETA: 0s - loss: 6.959232/32 [==============================] - 2s 4ms/step - loss: 6.9826
----------------------------- Captured stdout call -----------------------------
 1/32 [..............................] - ETA: 12s - loss: 7.962916/32 [==============>...............] - ETA: 0s - loss: 6.8616 32/32 [==============================] - 1s 3ms/step - loss: 6.8496
=============================== warnings summary ===============================
../../../../../../../../usr/local/lib/python3.11/site-packages/tensorflow/python/framework/dtypes.py:35
  /usr/local/lib/python3.11/site-packages/tensorflow/python/framework/dtypes.py:35: DeprecationWarning: ml_dtypes.float8_e4m3b11 is deprecated. Use ml_dtypes.float8_e4m3b11fnuz
    from tensorflow.tsl.python.lib.core import pywrap_ml_dtypes

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
- generated xml file: /Users/alikhan/Documents/Lambton_College/3rd_semester/CI:CD/CA_1/regression_project/junit/test-results.xml -

---------- coverage: platform darwin, python 3.11.2-final-0 ----------

=========================== short test summary info ============================
FAILED tests/test_regression_project.py::test_regression_model_training - ass...
=================== 1 failed, 3 passed, 1 warning in 21.31s ====================
